// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAQdtdkzbwufuZKvWK9ylWHqhLPKcXmwY',
    appId: '1:1041335979454:web:ba45d364a3238ede55bdef',
    messagingSenderId: '1041335979454',
    projectId: 'final-project-velo',
    authDomain: 'final-project-velo.firebaseapp.com',
    storageBucket: 'final-project-velo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Up6opjgUnbl0prVBOrXvPIqI_5Y8Pkw',
    appId: '1:1041335979454:android:532e2413369f03c055bdef',
    messagingSenderId: '1041335979454',
    projectId: 'final-project-velo',
    storageBucket: 'final-project-velo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt-JOECk-w4eyX6xlLFaJQix_Owf7MJhk',
    appId: '1:1041335979454:ios:22d3a0f07877d69455bdef',
    messagingSenderId: '1041335979454',
    projectId: 'final-project-velo',
    storageBucket: 'final-project-velo.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectVelotolouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt-JOECk-w4eyX6xlLFaJQix_Owf7MJhk',
    appId: '1:1041335979454:ios:22d3a0f07877d69455bdef',
    messagingSenderId: '1041335979454',
    projectId: 'final-project-velo',
    storageBucket: 'final-project-velo.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectVelotolouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAQdtdkzbwufuZKvWK9ylWHqhLPKcXmwY',
    appId: '1:1041335979454:web:ea203001cf6f384855bdef',
    messagingSenderId: '1041335979454',
    projectId: 'final-project-velo',
    authDomain: 'final-project-velo.firebaseapp.com',
    storageBucket: 'final-project-velo.firebasestorage.app',
  );
}
